#!/usr/bin/python

# Generate an MRTG config file including all important counters of ifTable

# Copyright 2011 Marlon Dutra
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from optparse import OptionParser
from pprint import pprint
import netsnmp # apt-get install libsnmp-python
import sys
import datetime

parser = OptionParser()

parser.add_option('-c', '--community', default='public')

(options, args) = parser.parse_args()

host = args[0]

ifTable = netsnmp.VarList('.1.3.6.1.2.1.2.2')
sysName = netsnmp.Varbind('.1.3.6.1.2.1.1.5.0')

netsnmp.snmpwalk(ifTable, Version=1, DestHost=host, Community=options.community)
netsnmp.snmpget(sysName, Version=1, DestHost=host, Community=options.community)
sysName = sysName.val

ifData = {}
for a in ifTable:
	if not ifData.has_key(a.tag):
		ifData[a.tag] = {}

	ifData[a.tag][a.iid] = a.val

# debug # pprint(ifData)

print '''# MRTG config file generated by cfgmaker-iftable
# sysName: %s
# %s
''' % (sysName, datetime.datetime.now())

print 'WorkDir: /var/www/mrtg/%s-ifTable' % (sysName)
print 'EnableIPv6: no'
print

iids = sorted(ifData['ifIndex'].keys())
for iid in iids:
	ifName = ifData['ifDescr'][iid]
	ifName = ifName.replace('/', '_')
	ifName = ifName.replace('.', '_')

	print '# %s (id %s)' % (ifData['ifDescr'][iid], iid)
	print

	# octets

	print 'Target[%s_%s_ifOctets]: .1.3.6.1.2.1.2.2.1.10.%s&.1.3.6.1.2.1.2.2.1.16.%s:%s@%s' % (sysName, ifName, iid, iid, options.community, host)
	print 'MaxBytes[%s_%s_ifOctets]: %d' % (sysName, ifName, int(ifData['ifSpeed'][iid]) / 8)
	print 'Title[%s_%s_ifOctets]: %s -- %s -- ifOctets' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'PageTop[%s_%s_ifOctets]: <h1>%s -- %s -- ifOctets</h1>' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'Options[%s_%s_ifOctets]: growright, bits' % (sysName, ifName)
	print

	# packets/sec (ifUcastPkts + ifNUcastPkts)

	print 'Target[%s_%s_ifPkts]: .1.3.6.1.2.1.2.2.1.11.%s&.1.3.6.1.2.1.2.2.1.17.%s:%s@%s' % (sysName, ifName, iid, iid, options.community, host) + ' + ' + '.1.3.6.1.2.1.2.2.1.12.%s&.1.3.6.1.2.1.2.2.1.18.%s:%s@%s' % (iid, iid, options.community, host)
	print 'MaxBytes[%s_%s_ifPkts]: 4294967296' % (sysName, ifName)
	print 'Title[%s_%s_ifPkts]: %s -- %s -- ifPkts' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'PageTop[%s_%s_ifPkts]: <h1>%s -- %s -- ifPkts</h1>' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'Options[%s_%s_ifPkts]: growright, nolegend' % (sysName, ifName)
	print 'YLegend[%s_%s_ifPkts]: pkt/sec' % (sysName, ifName)
	print 'ShortLegend[%s_%s_ifPkts]: pkt/sec' % (sysName, ifName)
	print

	# discards

	print 'Target[%s_%s_ifDiscards]: .1.3.6.1.2.1.2.2.1.13.%s&.1.3.6.1.2.1.2.2.1.19.%s:%s@%s' % (sysName, ifName, iid, iid, options.community, host)
	print 'MaxBytes[%s_%s_ifDiscards]: 4294967296' % (sysName, ifName)
	print 'Title[%s_%s_ifDiscards]: %s -- %s -- ifDiscards' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'PageTop[%s_%s_ifDiscards]: <h1>%s -- %s -- ifDiscards</h1>' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'Options[%s_%s_ifDiscards]: growright, nolegend' % (sysName, ifName)
	print 'YLegend[%s_%s_ifDiscards]: discards/sec' % (sysName, ifName)
	print 'ShortLegend[%s_%s_ifDiscards]: discards/sec' % (sysName, ifName)
	print

	# errors

	print 'Target[%s_%s_ifErrors]: .1.3.6.1.2.1.2.2.1.14.%s&.1.3.6.1.2.1.2.2.1.20.%s:%s@%s' % (sysName, ifName, iid, iid, options.community, host)
	print 'MaxBytes[%s_%s_ifErrors]: 4294967296' % (sysName, ifName)
	print 'Title[%s_%s_ifErrors]: %s -- %s -- ifErrors' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'PageTop[%s_%s_ifErrors]: <h1>%s -- %s -- ifErrors</h1>' % (sysName, ifName, sysName, ifData['ifDescr'][iid])
	print 'Options[%s_%s_ifErrors]: growright, nolegend' % (sysName, ifName)
	print 'YLegend[%s_%s_ifErrors]: errors/sec' % (sysName, ifName)
	print 'ShortLegend[%s_%s_ifErrors]: errors/sec' % (sysName, ifName)
	print

print >> sys.stderr, 'Do not forget to mkdir /var/www/mrtg/%s-ifTable' % (sysName)
