#!/usr/bin/python3

# TCP knock ports

# Copyright 2011 Marlon Dutra
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import socket
import sys

if len(sys.argv) < 3:
	print('Usage: %s IP port1 port2 portN...' % sys.argv[0], file=sys.stderr)
	sys.exit(1)

host = sys.argv[1]
ports = map(int, sys.argv[2:])

print('Knocking %s at ports %s' % (host, ', '.join(map(str, ports))))

for port in ports:
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.setblocking(0)
	s.connect_ex((host, port))
