#!/bin/bash

# Convert whatever mplayer can read to a MPEG4 with high quality. Useful to
# compress HD/FULL HD movies

# Copyright 2011 Marlon Dutra
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ -z "$2" ]
then
	echo "Usage: $0 input output"
	exit 1
fi

mencoder "$1" -o "$2" -ovc lavc -lavcopts vcodec=mpeg4:vbitrate=8000 -oac mp3lame -lameopts cbr:br=128
