#!/usr/bin/python

# Add GPS tags to jpeg photos

# Copyright 2011 Marlon Dutra
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import re

def usage():
	print >> sys.stderr, sys.argv[0] + ' latitude longitute file1 file2 fileN...\n'
	print >> sys.stderr, 'latitude/longitute format: D:M:S or -D:M:S'
	sys.exit(1)

if len(sys.argv) < 4:
	usage()

latlonre = re.compile('^[+-]?(\d+):(\d+):(\d+\.\d+)$')

lat = sys.argv[1]
lon = sys.argv[2]

latx = latlonre.search(lat)
lonx = latlonre.search(lon)

if not latx or not lonx:
	print >> sys.stderr, 'Error in lat/lon format'
	usage()

latref = ''
lonref = ''

if lat[0] == '-':
	latref = 'set Exif.GPSInfo.GPSLatitudeRef S'
else:
	latref = 'set Exif.GPSInfo.GPSLatitudeRef N'

if lon[0] == '-':
	lonref = 'set Exif.GPSInfo.GPSLongitudeRef W'
else:
	lonref = 'set Exif.GPSInfo.GPSLongitudeRef E'

latseg = int(float(latx.groups()[2]) * 100)
lonseg = int(float(lonx.groups()[2]) * 100)

latstr = 'set Exif.GPSInfo.GPSLatitude %s/1 %s/1 %s/100' % (latx.groups()[0], latx.groups()[1], latseg)
lonstr = 'set Exif.GPSInfo.GPSLongitude %s/1 %s/1 %s/100' % (lonx.groups()[0], lonx.groups()[1], lonseg)

#print latstr
#print latref
#print lonstr
#print lonref

for file in sys.argv[3:]:
	print file
	os.system('exiv2 -M"%s" -M"%s" -M"%s" -M"%s" %s' % (latstr, latref, lonstr, lonref, file))
